id: P009632
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-19 20:41:55.543479
source_metadata:
  id: bdr:W1KG12428
  title: མཐའ་མཚམས་ཞིབ་འཇུག་གི་དཔྱད་རྩོམ།
  author: ''
  volumes:
    d3f54744e4b141abba4501fc50663811:
      image_group_id: I1KG12457
      title: ''
      volume_number: 1
      total_pages: 47
      base_file: v001.txt
    0906a1dd31294c2eae2815d982929a5f:
      image_group_id: I1KG12458
      title: ''
      volume_number: 2
      total_pages: 71
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
