id: IF481AF01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:12:42+00:00'
last_modified: '2022-06-08T12:24:22.885068+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12428
  title: མཐའ་མཚམས་ཞིབ་འཇུག་གི་དཔྱད་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    208C:
      image_group_id: I1KG12457
      title: ''
      total_pages: 47
      order: 1
      base_file: 208C.txt
    59AE:
      image_group_id: I1KG12458
      title: ''
      total_pages: 71
      order: 2
      base_file: 59AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
